<a href="https://colab.research.google.com/github/Jayaprakash1710/Module-7-Common-Core-Foundations-NS/blob/main/Numpy_3_Image_Manipulation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import numpy as np

**np.any() np.all()**

In [8]:
a=np.array([1,10,5,9])
b=np.array([12,13,43,5])
print(a)
print(b)

[ 1 10  5  9]
[12 13 43  5]


In [9]:
a<b

array([ True,  True,  True, False])

In [10]:
c=np.array([12,13,43,5,6])
print(c)

[12 13 43  5  6]


In [11]:
a<c

ValueError: operands could not be broadcast together with shapes (4,) (5,) 

In [13]:
np.any(a<b)

True

In [14]:
np.all(a<b)

False

In [15]:
a=np.array([1,2,3,2])
b=np.array([2,2,3,2])
c=np.array([6,4,4,5])

In [16]:
a<=b

array([ True,  True,  True,  True])

In [17]:
b<=c

array([ True,  True,  True,  True])

In [18]:
np.all((a<=b) & (b<=c))

True

**argsort:**

In [19]:
a=np.array([10,9,5,11,3,6,1])
print(a)

[10  9  5 11  3  6  1]


In [20]:
np.sort(a)

array([ 1,  3,  5,  6,  9, 10, 11])

In [21]:
np.argmax(a)

3

In [22]:
np.argmin(a)

6

In [23]:
np.argsort(a)

array([6, 4, 2, 5, 1, 0, 3])

**Fitbit:**

In [25]:
data=np.loadtxt("/content/fit.txt",dtype='str')

In [26]:
data

array([['06-10-2017', '5464', 'Neutral', '181', '5', 'Inactive'],
       ['07-10-2017', '6041', 'Sad', '197', '8', 'Inactive'],
       ['08-10-2017', '25', 'Sad', '0', '5', 'Inactive'],
       ['09-10-2017', '5461', 'Sad', '174', '4', 'Inactive'],
       ['10-10-2017', '6915', 'Neutral', '223', '5', 'Active'],
       ['11-10-2017', '4545', 'Sad', '149', '6', 'Inactive'],
       ['12-10-2017', '4340', 'Sad', '140', '6', 'Inactive'],
       ['13-10-2017', '1230', 'Sad', '38', '7', 'Inactive'],
       ['14-10-2017', '61', 'Sad', '1', '5', 'Inactive'],
       ['15-10-2017', '1258', 'Sad', '40', '6', 'Inactive'],
       ['16-10-2017', '3148', 'Sad', '101', '8', 'Inactive'],
       ['17-10-2017', '4687', 'Sad', '152', '5', 'Inactive'],
       ['18-10-2017', '4732', 'Happy', '150', '6', 'Active'],
       ['19-10-2017', '3519', 'Sad', '113', '7', 'Inactive'],
       ['20-10-2017', '1580', 'Sad', '49', '5', 'Inactive'],
       ['21-10-2017', '2822', 'Sad', '86', '6', 'Inactive'],
       ['22-10

In [27]:
data.shape

(96, 6)

In [32]:
date,steps_count,mood,calories_burnt,hours_slept,activity=data.T

In [33]:
date

array(['06-10-2017', '07-10-2017', '08-10-2017', '09-10-2017',
       '10-10-2017', '11-10-2017', '12-10-2017', '13-10-2017',
       '14-10-2017', '15-10-2017', '16-10-2017', '17-10-2017',
       '18-10-2017', '19-10-2017', '20-10-2017', '21-10-2017',
       '22-10-2017', '23-10-2017', '24-10-2017', '25-10-2017',
       '26-10-2017', '27-10-2017', '28-10-2017', '29-10-2017',
       '30-10-2017', '31-10-2017', '01-11-2017', '02-11-2017',
       '03-11-2017', '04-11-2017', '05-11-2017', '06-11-2017',
       '07-11-2017', '08-11-2017', '09-11-2017', '10-11-2017',
       '11-11-2017', '12-11-2017', '13-11-2017', '14-11-2017',
       '15-11-2017', '16-11-2017', '17-11-2017', '18-11-2017',
       '19-11-2017', '20-11-2017', '21-11-2017', '22-11-2017',
       '23-11-2017', '24-11-2017', '25-11-2017', '26-11-2017',
       '27-11-2017', '28-11-2017', '29-11-2017', '30-11-2017',
       '01-12-2017', '02-12-2017', '03-12-2017', '04-12-2017',
       '05-12-2017', '06-12-2017', '07-12-2017', '08-12

In [34]:
steps_count=np.array(steps_count,dtype='int')
calories_burnt=np.array(calories_burnt,dtype='int')
hours_slept=np.array(hours_slept,dtype='int')

**Mood:**

In [35]:
np.unique(mood)

array(['Happy', 'Neutral', 'Sad'], dtype='<U10')

In [36]:
np.unique(mood,return_counts=True)

(array(['Happy', 'Neutral', 'Sad'], dtype='<U10'), array([40, 27, 29]))

**Steps ount:**

In [37]:
np.mean(steps_count)

2935.9375

In [38]:
np.max(steps_count)

7422

In [39]:
np.min(steps_count)

25

In [40]:
np.argmax(steps_count)

69

In [41]:
date[np.argmax(steps_count)]

'14-12-2017'

In [42]:
date[np.argmin(steps_count)]

'08-10-2017'

In [43]:
calories_burnt[np.argmin(steps_count)]

0

In [44]:
calories_burnt[np.argmax(steps_count)]

243

In [45]:
mood[np.argmax(steps_count)]

'Happy'

In [46]:
mood[np.argmin(steps_count)]

'Sad'

Mean value of step counts when mood is 'sad'

In [50]:
np.mean(steps_count[mood=='Sad'])

2103.0689655172414

In [51]:
np.mean(steps_count[mood=='Happy'])

3392.725

In [53]:
np.mean(steps_count[mood=='Neutral'])

3153.777777777778

**Mood with respect to steps:**

In [58]:
np.unique(mood[steps_count>4000],return_counts=True)

(array(['Happy', 'Neutral', 'Sad'], dtype='<U10'), array([22,  9,  7]))

In [59]:
np.unique(mood[steps_count<2000],return_counts=True)

(array(['Happy', 'Neutral', 'Sad'], dtype='<U10'), array([13,  8, 18]))

**Mood with respect to sleep:**

In [63]:
np.unique(mood[hours_slept<4],return_counts=True)

(array(['Happy', 'Neutral', 'Sad'], dtype='<U10'), array([1, 5, 6]))

In [64]:
np.unique(mood[hours_slept<5],return_counts=True)

(array(['Happy', 'Neutral', 'Sad'], dtype='<U10'), array([ 7,  9, 10]))

In [69]:
np.unique(mood[hours_slept>=5],return_counts=True)

(array(['Happy', 'Neutral', 'Sad'], dtype='<U10'), array([33, 18, 19]))

In [67]:
np.unique(mood[hours_slept<=6],return_counts=True)

(array(['Happy', 'Neutral', 'Sad'], dtype='<U10'), array([30, 25, 24]))

In [68]:
np.unique(mood[hours_slept>=6],return_counts=True)

(array(['Happy', 'Neutral', 'Sad'], dtype='<U10'), array([20,  3, 10]))

**3D-array:**

In [70]:
a=np.arange(24).reshape(2,3,4)
print(a)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [71]:
a.size

24

In [72]:
a.ndim

3

In [73]:
a.shape

(2, 3, 4)

In [74]:
len(a)

2