<a href="https://colab.research.google.com/github/Jayaprakash1710/Module-7-Common-Core-Foundations-NS/blob/main/Numpy_2_Airbnb's_NPS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Lecture:

In [25]:
import numpy as np

In [26]:
a=np.arange(1,13)
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


**Dimension:**

np.ndim(arr)

In [27]:
a.ndim

1

**Shape:**

arr.shape

In [28]:
a.shape

(12,)

shape of the dataset or a variable is represented in a tuple. (15) doesn't look like a tuple (15,) now it is a tuple.

**Indexing and slicing:**

In [29]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [30]:
a[2]

3

In [31]:
a[-1]

12

In [32]:
a[3]

4

Selecting elements with multiple indices:

In [33]:
a[[2,5,9]]

array([ 3,  6, 10])

In [34]:
a[[-10,-7,-3]]

array([ 3,  6, 10])

In [35]:
a[[2,5,9,2]] #taking an index twice

array([ 3,  6, 10,  3])

In [36]:
a[[2,5,9,-10]] #mix of negative and positive index

array([ 3,  6, 10,  3])

Slicing:

In [37]:
a[::]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [38]:
a[:5]

array([1, 2, 3, 4, 5])

In [39]:
a[0:0]

array([], dtype=int64)

In [40]:
a[::-1]

array([12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [41]:
a[:12:-1]

array([], dtype=int64)

In [42]:
a[2:6:2]

array([3, 5])

In [43]:
a[-2:-7:-1]

array([11, 10,  9,  8,  7])

In [44]:
a[-2:-7:-2]

array([11,  9,  7])

In [45]:
a[-2:7:-1]

array([11, 10,  9])

In [46]:
a[-5:10:1]

array([ 8,  9, 10])

In [47]:
a[7:2:-2]

array([8, 6, 4])

**Fancy Indexing or Masking:**

In [51]:
a<6

array([ True,  True,  True,  True,  True, False, False, False, False,
       False, False, False])

In [50]:
a[a<6]

array([1, 2, 3, 4, 5])

In [52]:
a%2==0

array([False,  True, False,  True, False,  True, False,  True, False,
        True, False,  True])

In [53]:
a[a%2==0]

array([ 2,  4,  6,  8, 10, 12])

In [55]:
a[~a%2!=0]

array([ 2,  4,  6,  8, 10, 12])

**And:**

'&' is used t compare elemnt wise where as 'and' compares the whole object

In [64]:
mask_1=a%2==0
mask_2=a%5==0

a[mask_1 & mask_2]

array([10])

In [74]:
a[(a%2==0)&(a%5==0)]

array([10])

**Or:**

In [65]:
a[mask_1 | mask_2]

array([ 2,  4,  5,  6,  8, 10, 12])

In [75]:
a[(a%2==0)|(a%5==0)]

array([ 2,  4,  5,  6,  8, 10, 12])

**Universal Functions:**

In [76]:
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [77]:
np.add(a,2)

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [78]:
np.sum(a)

78

In [84]:
a.sum()

78

In [79]:
np.mean(a)

6.5

In [85]:
a.mean()

6.5

In [80]:
np.median(a)

6.5

In [87]:
a.median()

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [82]:
np.min(a)

1

In [88]:
a.min()

1

In [83]:
np.max(a)

12

In [89]:
a.max()

12

In [90]:
b=np.array([13,9,3,6,8,7,12,45,22,19])
print(b)

[13  9  3  6  8  7 12 45 22 19]


In [92]:
np.sort(b)

array([ 3,  6,  7,  8,  9, 12, 13, 19, 22, 45])

In [94]:
b.sort() #doesn't provide any output but does an inplace sort

In [95]:
print(b)

[ 3  6  7  8  9 12 13 19 22 45]


# Working on Dataset:

In [102]:
feedback=np.loadtxt("/content/survey.txt",dtype='int64')

In [103]:
feedback

array([ 7, 10,  5, ...,  5,  9, 10])

In [110]:
participants=len(feedback)
print(participants)

1167


In [111]:
promoters=len(feedback[feedback>=9])
print(promoters)
detractors=len(feedback[feedback<=6])
print(detractors)

609
332


In [112]:
NPS=(promoters/participants)*100-(detractors/participants)*100
print(NPS)

23.73607540702657
