<a href="https://colab.research.google.com/github/Jayaprakash1710/Module-7-Common-Core-Foundations-NS/blob/main/Numpy_3_Airbnb's_NPS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

**np.empty()**

In [3]:
feedback=np.loadtxt('/content/survey.txt',dtype='int64')
feedback

array([ 7, 10,  5, ...,  5,  9, 10])

In [21]:
labels=np.empty(shape=feedback.shape[0],dtype='U21')
labels

array(['', '', '', ..., '', '', ''], dtype='<U21')

In [22]:
labels[feedback<7]='detractors'
labels[feedback>8]='promoters'
labels[(feedback>6)&(feedback<9)]='neutrals'

In [23]:
labels

array(['neutrals', 'promoters', 'detractors', ..., 'detractors',
       'promoters', 'promoters'], dtype='<U21')

In [24]:
labels.unique()

AttributeError: 'numpy.ndarray' object has no attribute 'unique'

In [26]:
np.unique(labels)

array(['detractors', 'neutrals', 'promoters'], dtype='<U21')

In [28]:
np.unique(labels,return_counts=True)

(array(['detractors', 'neutrals', 'promoters'], dtype='<U21'),
 array([332, 226, 609]))

In [29]:
np.value_count(labels)

AttributeError: module 'numpy' has no attribute 'value_count'

Quiz:1

In [31]:
arr=np.array([1,2,3,4,5,6,7,8])
print(arr.ndim,arr.shape)

1 (8,)


Quiz:2

In [34]:
a=np.array([1,2,3,4,5])
b=np.array([8,7,6])
a[2:]=b[::-1]
print(a)

[1 2 6 7 8]


**2d arrays:**

In [36]:
a=np.array([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [37]:
b=np.array([[1,2,3],[4,5]])
print(b)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [38]:
print(a.ndim)
print(a.shape)

2
(2, 3)


In [39]:
print(a.size)

6


In [40]:
print(len(a))

2
