<a href="https://colab.research.google.com/github/Jayaprakash1710/Module-7-Common-Core-Foundations-NS/blob/main/Numpy_1_Airbnb's_NPS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Lecture:

**Business Case: Calculate NPS for NPS**

NPS= %Promoters-%Detractors

*   Promoters: 9-10
*   Detractors: 1-6
*   Passive: 7-8







In [1]:
import numpy as np

**Why NumPy?**

Numpy supports element wise operation.

In [2]:
a=[1,2,3,4,5] #python list

I want [1,4,9,16,25] which is a**2

In [3]:
a**2

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

Python list doesn't support element wise operation. To achive the square of all numbers we need to use for loop.

In [4]:
b=[i**2 for i in a]
print(b)

[1, 4, 9, 16, 25]


Now let's try to do the same thing using NumPy

In [5]:
c=np.array([1,2,3,4,5])
print(c**2)

[ 1  4  9 16 25]


In [6]:
print(type(a))
print(type(c))

<class 'list'>
<class 'numpy.ndarray'>


a is a list but c is a NumPy array. NumPy array supports element wise operations where as python lists deosn't.

Few more examples:

adding 2 arrays

In [7]:
a=[1,2,3,4,5,6]
b=[6,7,8,9,10]
print(a+b)

[1, 2, 3, 4, 5, 6, 6, 7, 8, 9, 10]


In [8]:
c=np.array([1,2,3,4,5])
d=np.array([6,7,8,9,10])
print(c+d)

[ 7  9 11 13 15]


List comprehension and loops are not needed here for element wise operation

Timing difference:

In [9]:
a=range(100000)
print(a)

range(0, 100000)


In [10]:
%timeit [i**2 for i in a]

3.49 ms ± 63 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [11]:
b=np.arange(100000)
print(b)

[    0     1     2 ... 99997 99998 99999]


In [12]:
%timeit b**2

29 µs ± 646 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


NumPy did element wise operation faster than List

List-millisecond

NumPy array-microsecond

**Homogenetiy and Heterogenity:**

In [13]:
l=[1,2,3.4,'Jayapraksh',True]
print(l)

[1, 2, 3.4, 'Jayapraksh', True]


In [14]:
z=np.array([1,2,3.4,'Jayaprakash',True])
print(z)

['1' '2' '3.4' 'Jayaprakash' 'True']


Everything got converted to string in numpy array. Numpy array is homogenous, it can't contain data with multiple datatype.

**Why NumPy is fast?**



*   NumPy is built using the language **C**
*   Data type of all the elements are same (stores only one data type)



In [18]:
a=np.array([1,2,3,4,5,6])
print(a.dtype) # to get the data type of the elements stored in a
print(type(a)) # to get the data type of the variable a

int64
<class 'numpy.ndarray'>


In [20]:
b=np.array([2.0,3.0,4.0])
print(b.dtype)

float64


In [29]:
c=np.array(['Bala','Sala','Wala'])
print(c)
print(c.dtype)

['Bala' 'Sala' 'Wala']
<U4


Order: bool<int<float<string

**Setting datatype:**

In [31]:
d=np.array([1,2,3,4,5],dtype='float')
print(d)
print(d.dtype)

[1. 2. 3. 4. 5.]
float64


In [32]:
e=np.array([1,2,3,4,5],dtype='str')
print(e)
print(e.dtype)

['1' '2' '3' '4' '5']
<U1


In [33]:
f=np.array(['JP','PP'],dtype='int')
print(f)
print(f.dtype)

ValueError: invalid literal for int() with base 10: 'JP'

**range and arange:**

In [34]:
range(100)

range(0, 100)

In [35]:
range(1,100)

range(1, 100)

In [36]:
range(1,100,2)

range(1, 100, 2)

In [38]:
np.arange(100)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [39]:
np.arange(1,100)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [40]:
np.arange(1,100,3)

array([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49,
       52, 55, 58, 61, 64, 67, 70, 73, 76, 79, 82, 85, 88, 91, 94, 97])

In [41]:
np.arange(1,10,0.3)

array([1. , 1.3, 1.6, 1.9, 2.2, 2.5, 2.8, 3.1, 3.4, 3.7, 4. , 4.3, 4.6,
       4.9, 5.2, 5.5, 5.8, 6.1, 6.4, 6.7, 7. , 7.3, 7.6, 7.9, 8.2, 8.5,
       8.8, 9.1, 9.4, 9.7])

In [43]:
arange(1,10,0.5)

NameError: name 'arange' is not defined

In [42]:
np.arange(1,10,0.5)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. ,
       7.5, 8. , 8.5, 9. , 9.5])

arange supports step size in float whereas range doesn't

# Assignments:

## Q-1:
Which of the following option(s) can add 1 to each element of array A?

A = np.array([2, 0, 1, 9, 1, 1, 1, 0, 3, 5])



1.   A+1
2.   list(map(lambda x:x+1,A))


3.   [x+1 for x in A]
4.   A+"1





In [44]:
A = np.array([2, 0, 1, 9, 1, 1, 1, 0, 3, 5])

In [45]:
print(A+1)

[ 3  1  2 10  2  2  2  1  4  6]


In [46]:
b=list(map(lambda x:x+1,A))
print(b)

[3, 1, 2, 10, 2, 2, 2, 1, 4, 6]


In [47]:
c=[x+1 for x in A]
print(c)

[3, 1, 2, 10, 2, 2, 2, 1, 4, 6]


In [48]:
print(A+"1")

UFuncTypeError: ufunc 'add' did not contain a loop with signature matching types (dtype('int64'), dtype('<U1')) -> None