<a href="https://colab.research.google.com/github/Jayaprakash1710/Module-7-Common-Core-Foundations-NS/blob/main/Numpy_3_Airbnb's_NPS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

**np.empty()**

In [4]:
feedback=np.loadtxt('/content/survey.txt',dtype='int64')
feedback

array([ 7, 10,  5, ...,  5,  9, 10])

In [5]:
labels=np.empty(shape=feedback.shape[0],dtype='U21')
labels

array(['', '', '', ..., '', '', ''], dtype='<U21')

In [6]:
labels[feedback<7]='detractors'
labels[feedback>8]='promoters'
labels[(feedback>6)&(feedback<9)]='neutrals'

In [7]:
labels

array(['neutrals', 'promoters', 'detractors', ..., 'detractors',
       'promoters', 'promoters'], dtype='<U21')

In [8]:
labels.unique()

AttributeError: 'numpy.ndarray' object has no attribute 'unique'

In [9]:
np.unique(labels)

array(['detractors', 'neutrals', 'promoters'], dtype='<U21')

In [10]:
np.unique(labels,return_counts=True)

(array(['detractors', 'neutrals', 'promoters'], dtype='<U21'),
 array([332, 226, 609]))

In [11]:
np.value_count(labels)

AttributeError: module 'numpy' has no attribute 'value_count'

Quiz:1

In [13]:
arr=np.array([1,2,3,4,5,6,7,8])
print(arr.ndim,arr.shape)

1 (8,)


Quiz:2

In [14]:
a=np.array([1,2,3,4,5])
b=np.array([8,7,6])
a[2:]=b[::-1]
print(a)

[1 2 6 7 8]


**2d arrays:**

In [15]:
a=np.array([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [16]:
b=np.array([[1,2,3],[4,5]])
print(b)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [17]:
print(a.ndim)
print(a.shape)

2
(2, 3)


In [18]:
print(a.size)

6


In [19]:
print(len(a))

2


**reshape:**

In [20]:
a.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [21]:
a.reshape(1,6)

array([[1, 2, 3, 4, 5, 6]])

In [22]:
a.reshape(6,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [23]:
c=np.arange(1,13).reshape(3,4)
c

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

reshaping with all the factors are possible

In [24]:
c.reshape(6,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

-1 as a placeholder

In [25]:
c.reshape(-1,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [26]:
c.reshape(4,-1)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

**arr.T - Transpose**

In [27]:
c

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [28]:
c.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [30]:
a=a.flatten()

In [31]:
a

array([1, 2, 3, 4, 5, 6])

In [32]:
a.T

array([1, 2, 3, 4, 5, 6])

In [33]:
a=a.reshape(1,6)
print(a)

[[1 2 3 4 5 6]]


In [34]:
a.T

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

**Indexing and Slicing: 2D**

In [36]:
a=np.arange(1,13).reshape(3,-1)
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [38]:
a[1][1] #two step process

6

In [39]:
a[1,1]

6

In [40]:
a[2,2]

11

In [41]:
a[-1,-2]

11

In [48]:
a[[1,2,0],[1,3,3]]

array([ 6, 12,  4])

slicing:

In [49]:
a[:,:]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [50]:
a[1:,:]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [51]:
a[1:,1:]

array([[ 6,  7,  8],
       [10, 11, 12]])

In [52]:
a[1::,1::2]

array([[ 6,  8],
       [10, 12]])

In [53]:
a[1::,::-1]

array([[ 8,  7,  6,  5],
       [12, 11, 10,  9]])

In [54]:
a[::2,::-2]

array([[ 4,  2],
       [12, 10]])

In [55]:
a[::-1,::-2]

array([[12, 10],
       [ 8,  6],
       [ 4,  2]])

Homework:

In [56]:
a[::-1][::-2]

array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

In [61]:
b=a[::-1]
b

array([[ 9, 10, 11, 12],
       [ 5,  6,  7,  8],
       [ 1,  2,  3,  4]])

In [62]:
b[::-2]

array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

**Fancy Indexing and masking:2D**

In [63]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [64]:
a<7

array([[ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False]])

In [65]:
a[a<7]

array([1, 2, 3, 4, 5, 6])

**Axis:**

In [66]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

Vertical: axis=0

Horizontal: axis=1

In [67]:
np.sum(a)

78

In [68]:
np.sum(a,axis=0)

array([15, 18, 21, 24])

In [69]:
np.sum(a,axis=1)

array([10, 26, 42])

In [70]:
np.min(a)

1

In [71]:
np.min(a,axis=0)

array([1, 2, 3, 4])

In [72]:
np.min(a,axis=1)

array([1, 5, 9])

In [73]:
np.sort(a,axis=0)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [74]:
z=np.array([[3,8,12,5],[91,1,3,4],[8,6,10,18]])
print(z)

[[ 3  8 12  5]
 [91  1  3  4]
 [ 8  6 10 18]]


In [75]:
np.sort(z,axis=0)

array([[ 3,  1,  3,  4],
       [ 8,  6, 10,  5],
       [91,  8, 12, 18]])

In [76]:
np.sort(z,axis=1)

array([[ 3,  5,  8, 12],
       [ 1,  3,  4, 91],
       [ 6,  8, 10, 18]])